import Head from "next/head";

export default function Index() {
  return (
    <>
      <Head>
        <title>categories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello</h1>
    </>
  );
}